# Implementing complete and partial derivatives in python

In [75]:
def f(x):
    return x ** 2

In [76]:
def simple_derivative(f, x, h=1e-8):
    return (f(x) - f(x - h))/h

In [77]:
simple_derivative(f, 6)

11.99999957179898

In [78]:
def central_derivative(f, x, h=1e-8):
    return (f(x + h) - f(x - h))/( 2 * h )

In [79]:
central_derivative(f, 6)

11.999999927070348

In [80]:
def g(x):
    return (x[0] ** 2) + (3 * x[1] ** 2)

In [81]:
def partial_derivative(f, x, i, h=1e-5):
    x_plus = x.copy()
    x_minus = x.copy()
    x_plus[i] += h
    x_minus[i] -= h
    return (f(x_plus) - f(x_minus))/(2 * h)

In [82]:
partial_derivative(g, [3, 4], 1)

23.99999999909141

In [83]:
def gradient(f, x, h=1e-5):
    return [partial_derivative(f, x, i, h) for i in range(len(x))]

In [84]:
gradient(g, [3, 4])

[6.000000000128124, 23.99999999909141]

## Analytical Differentiation

In [85]:
import numpy as np

In [86]:
x = np.array([1, 2, 3, 4, 5])                          
y = np.array([2, 4, 6, 8, 10])

In [87]:
def predict(theta_0, theta_1, x):
    return theta_0 + (theta_1 * x)

In [88]:
def mse(theta_0, theta_1, x, y):
    return ((y - predict(theta_0, theta_1, x)) **2).mean()

In [89]:
def analytical_derivative(theta_0, theta_1, x, y):
    y_hat = predict(theta_0, theta_1, x)
    errors = y - y_hat
    d_theta_0 = -2 * errors.mean()
    d_theta_1 = -2 * (x * errors).mean()
    return d_theta_0, d_theta_1

In [90]:
analytical_derivative(0, 0, x, y)

(np.float64(-12.0), np.float64(-44.0))

In [91]:
analytical_derivative(0, 2, x, y)

(np.float64(-0.0), np.float64(-0.0))

In [92]:
J = lambda theta: mse(theta[0], theta[1], x, y)

In [93]:
gradient(J, [0.0, 0.0])

[np.float64(-11.999999999545706), np.float64(-44.00000000046588)]

In [94]:
analytical_derivative(0, 0, x, y)

(np.float64(-12.0), np.float64(-44.0))

### Autograd

In [95]:
import torch

a = torch.tensor([2., 3., 5.], requires_grad=True)
b = torch.tensor([6., 4., 8.], requires_grad=True)

In [96]:
loss = (a * b).mean()

In [97]:
loss

tensor(21.3333, grad_fn=<MeanBackward0>)

In [98]:
loss.backward()

In [99]:
a.grad

tensor([2.0000, 1.3333, 2.6667])

In [100]:
b.grad

tensor([0.6667, 1.0000, 1.6667])

In [101]:
theta_0 = torch.tensor(0., requires_grad=True)
theta_1 = torch.tensor(0., requires_grad=True)

In [102]:
x_t = torch.tensor(x, dtype=torch.float32)
y_t = torch.tensor(y, dtype=torch.float32)

In [103]:
y_hat = predict(theta_0, theta_1, x_t)
y_hat

tensor([0., 0., 0., 0., 0.], grad_fn=<AddBackward0>)

In [104]:
loss = mse(theta_0, theta_1, x_t, y_t)
loss

tensor(44., grad_fn=<MeanBackward0>)

In [105]:
loss.backward()

In [106]:
theta_0.grad

tensor(-12.)

In [107]:
theta_1.grad

tensor(-44.)